#use %timeleft% for the amount of time left till countdown
firstLine: "&c&lsome stuff"
secondLine: "&6Server releases in: %timeleft%"
#set the maximum slots to show the server as having, this does not stop people from joining!
slots: 1
#if this is true it overrides the above setting and makes the max slots the online playercount + slots (eg: 10 players are online. slots = 10 + slots)
variable-slots: true
#sets the hover messages
hovermessage: "Welcome to vectornetwork!"
#custom version name
version: "VectorNetwork 1.8.x - 1.15.x"

#date must be in this format "MM/dd/yy HH:mm:ss". The hour must be on a 24h clock. So if you wanted to do 5 PM,
#you would put hour 17.
date: '02/08/20 13:00:00'
#Use this list: https://publib.boulder.ibm.com/tividd/td/TWS/SC32-1274-02/en_US/HTML/SRF_mst273.htm
timezone: 'EST'

time-value-end: "Server is released!"